version: '3.8'
services:
  web:
    build: ./app
    volumes:
      - .:/usr/src
    ports:
      - 8000:8000
      - 5678:5678
    env_file:
      - app.env
    depends_on:
      - db
      - selenium

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - db.env

  selenium:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"

volumes:
  postgres_data:
