version: '3.8'
services:
  web:
    build: ./app
    volumes:
      - .:/usr/src
    ports:
      - 8000:8000
      - 5678:5678
    env_file:
      - app.env
    depends_on:
      - db
      - selenium
      - ollama
    networks:
      - medidas-net

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - db.env
    networks:
      - medidas-net

  selenium:
    image: selenium/standalone-chrome
    ports:
      - 4444:4444
    networks:
      - medidas-net

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    volumes:
      - ~/.ollama:/root/.ollama  # Mounting the Ollama model directory
    ports:
      - 11435:11434
    networks:
      - medidas-net

volumes:
  postgres_data:

networks:
  medidas-net:
    driver: bridge
